"""Initial migration

Revision ID: b2339f9bcce8
Revises: 
Create Date: 2026-01-11 10:35:57.393527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2339f9bcce8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS dev")
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.String(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dev'
    )
    op.create_index(op.f('ix_dev_sensor_readings_id'), 'sensor_readings', ['id'], unique=False, schema='dev')
    op.create_index(op.f('ix_dev_sensor_readings_sensor_id'), 'sensor_readings', ['sensor_id'], unique=False, schema='dev')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dev'
    )
    op.create_index(op.f('ix_dev_users_email'), 'users', ['email'], unique=True, schema='dev')
    op.create_index(op.f('ix_dev_users_full_name'), 'users', ['full_name'], unique=False, schema='dev')
    op.create_index(op.f('ix_dev_users_id'), 'users', ['id'], unique=False, schema='dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dev_users_id'), table_name='users', schema='dev')
    op.drop_index(op.f('ix_dev_users_full_name'), table_name='users', schema='dev')
    op.drop_index(op.f('ix_dev_users_email'), table_name='users', schema='dev')
    op.drop_table('users', schema='dev')
    op.drop_index(op.f('ix_dev_sensor_readings_sensor_id'), table_name='sensor_readings', schema='dev')
    op.drop_index(op.f('ix_dev_sensor_readings_id'), table_name='sensor_readings', schema='dev')
    op.drop_table('sensor_readings', schema='dev')
    # ### end Alembic commands ###
