"""Add irrigation_zones table

Revision ID: ea29d50fb25f
Revises: 666f0988181c
Create Date: 2026-01-11 21:52:02.649565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea29d50fb25f'
down_revision: Union[str, Sequence[str], None] = '666f0988181c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('irrigation_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_pump_active', sa.Boolean(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('last_watered', sa.DateTime(), nullable=True),
    sa.Column('timer_seconds_remaining', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dev'
    )
    op.create_index(op.f('ix_dev_irrigation_zones_id'), 'irrigation_zones', ['id'], unique=False, schema='dev')
    op.create_index(op.f('ix_dev_irrigation_zones_name'), 'irrigation_zones', ['name'], unique=False, schema='dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dev_irrigation_zones_name'), table_name='irrigation_zones', schema='dev')
    op.drop_index(op.f('ix_dev_irrigation_zones_id'), table_name='irrigation_zones', schema='dev')
    op.drop_table('irrigation_zones', schema='dev')
    # ### end Alembic commands ###
