"""Add last_login and user_messages

Revision ID: ec684a52f597
Revises: ea29d50fb25f
Create Date: 2026-01-11 22:17:06.852186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec684a52f597'
down_revision: Union[str, Sequence[str], None] = 'ea29d50fb25f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['dev.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dev'
    )
    op.create_index(op.f('ix_dev_user_messages_id'), 'user_messages', ['id'], unique=False, schema='dev')
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True), schema='dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login', schema='dev')
    op.drop_index(op.f('ix_dev_user_messages_id'), table_name='user_messages', schema='dev')
    op.drop_table('user_messages', schema='dev')
    # ### end Alembic commands ###
